### ISSUE TITLE
Inviting a player locks the pause screen with only option to log out

### ISSUE THREAD

**Issue by Reddykjp1617** [blaxxun-boop/Groups#12]
My friend and I ran into this issue earlier today. The game wont let whoever the invited person is past the pause menu, and the only option is to logout.

**Comment by blaxxun-boop** [comment]
Sounds like you are using AUGA, which is incompatible with pretty much every single mod that adds something to the UI.
I'd recommend to replace AUGA with minimal UI. You can make minimal UI look exactly like AUGA and it works with other mods that change the UI.
