### ISSUE TITLE
invite issue - pops up game exit prompt

### ISSUE THREAD

**Issue by dcgsteve** [blaxxun-boop/Groups#15]
There was an issue with some windowed resolutions. Should fixed in v1.1.5 now, thanks.

_Originally posted by @blaxxun-boop in https://github.com/blaxxun-boop/Groups/issues/2#issuecomment-1097197215_
           
Any chance you can have a look at this issue again please?

I have two friends, I invite one and it works fine, I invite the other and she gets the same exit game prompt.
We have tried changing her from fullscreen to windowed but still no good.

We are all using the same 1.1.14 through Thunderstore (and with all the same other plugins)

Anything I can check/debug/fix?

**Comment by blaxxun-boop** [comment]
Remove Auga. It doesn't work with any mod that touches the UI. You can replace it with minimal UI, which works with other mods changing the UI out of the box. It also has a Auga theme you can enable in the config, which makes it look exactly like Auga.

**Comment by dcgsteve** [comment]
Many thanks! Googling for the Auga theme for minimal UI as I must admit I do like it :)

Cheers for very useful mod!
