### ISSUE TITLE
Update needed with Valheim Patch 0.214.2

### ISSUE THREAD

**Issue by ValhallaCommunity** [blaxxun-boop/Groups#17]
Hey Blaxxun, 

Groups broke with recent valheim patch 0.214.2 as we probably expected :)

Here is the error log and screenshot of a group.

![image](https://user-images.githubusercontent.com/124803112/225174629-de42a15a-9706-4947-8a37-eb34ec913383.png)

```
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Groups.Interface+UpdateGroupDisplay.Postfix () (at <90b173be03694f81a1783c47442965b2>:0)
(wrapper dynamic-method) Hud.DMD<Hud::Update>(Hud)
```

**Comment by ValhallaCommunity** [comment]
I don't know if this error is also attributed to it:

```
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Groups.Map+ColorNames.Postfix (Character c, System.Collections.Generic.Dictionary`2[TKey,TValue] ___m_huds) (at <90b173be03694f81a1783c47442965b2>:0)
(wrapper dynamic-method) EnemyHud.DMD<EnemyHud::ShowHud>(EnemyHud,Character,bool)
EnemyHud.LateUpdate () (at <afd4e3f8ab8b460f8ff25d476fbd573e>:0)
```

**Comment by AzumattDev** [comment]
She pulled in my Pull Request in her own way (like usual) and it's been resolved, but the issue wasn't closed. I have closed my pull request since it's no longer needed.

Anyways, for those that come to this later, it's fixed.

**Comment by ValhallaCommunity** [comment]
Thank you Azu and Blaxxun! Appreciate it always, closing!!
