### ISSUE TITLE
Invite while using Auga

### ISSUE THREAD

**Issue by hsramm** [blaxxun-boop/Groups#19]
If one receives an invite while using the Auga mod, the box pops up asking the user if they want to quit the game. If you click "No", nothing happens and the box remains on the screen. You can't ESC out of it either, you're forced to press "Yes" and close the game.

**Comment by blaxxun-boop** [comment]
That's an issue in Auga, has nothing to do with Groups.
And I highly recommend to remove that mod. Auga doesn't work with any other mod that touches the UI ever so slightly. You can replace it with minimal UI, which has an Auga theme. Looks like Auga, but works with other mods.

**Comment by hsramm** [comment]
I figured it was. I just recently started getting into mods and didn't know that Minimal UI has an Auga theme. I will check it out, thanks!
