### ISSUE TITLE
Error on invite

### ISSUE THREAD

**Issue by krumen** [blaxxun-boop/Groups#2]
Hi, 

When I invite anyone with /invite, the window to exit the game pops up and you can only click Yes, then it kicks you out of the game. If you click no, it does nothing.

The same thing happens all the time I try to invite.

**Comment by blaxxun-boop** [comment]
There was an issue with some windowed resolutions. Should fixed in v1.1.5 now, thanks.

**Comment by dcgsteve** [comment]
Any chance we can re-open this issue?

I have two friends, I invite one and it works fine, I invite the other and she gets the same exit game prompt.
We have tried changing her from fullscreen to windowed but still no good.

We are all using the same 1.1.14 through Thunderstore (and with all the same other plugins)

Anything I can check/debug/fix?
