### ISSUE TITLE
Support for ValheimPlus (Please)

### ISSUE THREAD

**Issue by Sqwince** [blaxxun-boop/Groups#27]
I understand ValheimPlus official branch hasn't been updated in a while, but I am trying to use the latest branch/fork by Grantapher with this Groups 1.2.6 mod.  I get the following error when the server tries to load:

🟥 [Error  :  BenInEx] Could not load [Groups 1.2.6] because it is incompatible with: org.bepinex.plugins.valheim_plus 

ValheimPlus_Grantapher_Temporary v9.12.0 by Grantapher

is there any suggestions on getting this to work? (downgrading version of either mod is what I am thinking but not sure which pairs with what version)

**Comment by Snapman110** [comment]
+1
would love to be able to use this with [ValheimPlus_0.9.15.0](https://thunderstore.io/c/valheim/p/Grantapher/ValheimPlus_Grantapher_Temporary/) <3

**Comment by blaxxun-boop** [comment]
Not going to happen. Read https://github.com/blaxxun-boop/PassivePowers/issues/5 for more details and replace Valheim Plus with alternatives.

**Comment by Snapman110** [comment]
my hoster forces me to use Valheim+ (0.9.15.0) which runs great with the 50 mods i installed. even if i could replace it, i probably wouldnt because im not going to install and configure 150 mods just to get the same functionality. will have to stop using your mods then :c

**Comment by 12emerta** [comment]
@Snapman110 

In my opinion, its in pretty bad taste that this author forces users away from V+ when the mod _can_ work fine with V+.  I forked his code, and removed the forced incompatibility.  I only use a few features of V+, but this has been working on my dedi for my group.

See:
https://github.com/12emerta/Groups-Plus
https://thunderstore.io/c/valheim/p/12emerta/Groups_Plus/
