### ISSUE TITLE
Group Left onDeath 

### ISSUE THREAD

**Issue by heberholanda** [blaxxun-boop/Groups#3]
When dying, he is leaving the Group. Is it a bug? Do you think it's possible to keep the player in the Group?

**Comment by blaxxun-boop** [comment]
You are probably using ReviveAllies. That's a bug in that mod.

**Comment by heberholanda** [comment]
I don't use this one, could you tell me which Event? So I can find out which mod may be causing this conflict.

**Comment by blaxxun-boop** [comment]
Groups expects the character ZDO ID to be set. There are some mods that clear this value, for whatever reason. The value is usually just cleared on logout. And if you logout, you leave the group.

**Comment by HeberPcL** [comment]
Got it, from what I've seen it's ValheimPlus that's causing this.

**Comment by blaxxun-boop** [comment]
I've added a cache to the player stuff, so if a mod author has no clue what he is doing and deletes that stuff on death, it shouldn't cause you to leave your group anymore.
