### ISSUE TITLE
Group Position for Larger monitors

### ISSUE THREAD

**Issue by heberholanda** [blaxxun-boop/Groups#6]
I got some feedback, the group position for monitors larger than 22' is too center of the screen.

![Sem_titulo](https://user-images.githubusercontent.com/715547/163748428-c209b13d-a1b1-4a71-b8b1-7d2f7f797acd.jpg)

**Comment by blaxxun-boop** [comment]
It gets moved to the center of the screen, if it was outside of your screen by default. Just drag and drop it to wherever you want.
