### ISSUE TITLE
Skills

### ISSUE THREAD

**Issue by vitalikbyrevich** [blaxxun-boop/Groups#7]
When you are in a group and you die, there is a good chance of losing all skills (reset to zero), as well as resetting the character and flying valkyrie again. I had to remove the mod from the server. The test was on the 1.6 version. There are a minimum of mods on the server. There is no ValheimPlus or similar.

**Comment by blaxxun-boop** [comment]
Nah, Groups doesn't even touch your character or your skills or anything.
