### ISSUE TITLE
[Enhancement] Guilds

### ISSUE THREAD

**Issue by snoweuph** [blaxxun-boop/Groups#9]
I've stumbled across this Plugin/Mod while searching for a Mod that Handles Guild
- Guild Members with Ranks
- Guild Wards (can only be created by Guild Leader and Co Leader) (is to guildmembers like if they are permitted to the ward (they cant destroy the ward))
- Guild Portals (portals that can only be used by the Guild members (portals with same tag of diffrent guilds wont make problems))
- Guild Capes  and Banners

I've found some Mods, but they where outdated and didnt have more then 1 feature.

I myself know some C# and did work with Unity before. I've read that you guys allready started working on a guild feature, can I join in and help?

**Comment by blaxxun-boop** [comment]
Yes, we are working on a Guild mod. And yes, these features will be included one way or the other. Probably not in the mod itself, but it will come with an extensive API, which can be used by other mods. E.g. Guild Portals will be a thing through TargetPortal and Guild Wards will be a thing through WardIsLove for sure.

Thanks for offering your help, but it's not needed.

Cheers.

**Comment by snoweuph** [comment]
Is there a Table of Procees that can be watched like a Kanban board or a Discord Server where updates to the status will be posted ?
